2024-01-14 23:38:45,712  --  INFO -- Handled Unknown Exception
2024-01-14 23:38:45,713  --  WARNING -- Retrying du
2024-01-14 23:38:54,054  --  ERROR -- Error terminating service process.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\common\service.py", line 170, in _terminate_process
    self.process.terminate()
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1671, in terminate
    _winapi.TerminateProcess(self._handle, 1)
OSError: [WinError 6] The handle is invalid
