2024-01-14 23:38:45,712  --  INFO -- Handled Unknown Exception
2024-01-14 23:38:45,713  --  WARNING -- Retrying du
2024-01-14 23:38:54,054  --  ERROR -- Error terminating service process.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\common\service.py", line 170, in _terminate_process
    self.process.terminate()
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1671, in terminate
    _winapi.TerminateProcess(self._handle, 1)
OSError: [WinError 6] The handle is invalid
2024-01-15 00:36:37,764  --  INFO -- Handled Unknown Exception
2024-01-15 00:36:37,766  --  WARNING -- Retrying du
2024-01-15 00:58:07,461  --  INFO -- Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-01-15 00:58:07,464  --  INFO -- Added job "automation_process" to job store "default"
2024-01-15 00:58:07,464  --  INFO -- Scheduler started
2024-01-15 00:58:29,269  --  INFO -- Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-01-15 00:58:29,270  --  INFO -- Added job "automation_process" to job store "default"
2024-01-15 00:58:29,270  --  INFO -- Scheduler started
2024-01-15 00:59:00,019  --  INFO -- Running job "automation_process (trigger: cron[day_of_week='mon-sun', hour='0', minute='59'], next run at: 2024-01-15 00:59:00 WAT)" (scheduled at 2024-01-15 00:59:00+01:00)
2024-01-15 01:00:50,630  --  INFO -- Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-01-15 01:00:50,632  --  INFO -- Added job "automation_process" to job store "default"
2024-01-15 01:00:50,632  --  INFO -- Scheduler started
2024-01-15 01:01:00,017  --  INFO -- Running job "automation_process (trigger: cron[day_of_week='mon-sun', hour='1', minute='1'], next run at: 2024-01-15 01:01:00 WAT)" (scheduled at 2024-01-15 01:01:00+01:00)
2024-01-15 01:02:12,427  --  INFO -- Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-01-15 01:02:12,429  --  INFO -- Added job "automation_process" to job store "default"
2024-01-15 01:02:12,430  --  INFO -- Scheduler started
2024-01-15 01:02:19,473  --  INFO -- Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-01-15 01:02:19,475  --  INFO -- Added job "automation_process" to job store "default"
2024-01-15 01:02:19,475  --  INFO -- Scheduler started
2024-01-15 01:03:00,012  --  INFO -- Running job "automation_process (trigger: cron[day_of_week='mon-sun', hour='1', minute='3'], next run at: 2024-01-15 01:03:00 WAT)" (scheduled at 2024-01-15 01:03:00+01:00)
2024-01-15 01:04:10,610  --  INFO -- Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-01-15 01:04:10,612  --  INFO -- Added job "automation_process" to job store "default"
2024-01-15 01:04:10,612  --  INFO -- Scheduler started
2024-01-15 01:05:00,009  --  INFO -- Running job "automation_process (trigger: cron[day_of_week='mon-sun', hour='1', minute='5'], next run at: 2024-01-15 01:05:00 WAT)" (scheduled at 2024-01-15 01:05:00+01:00)
2024-01-15 01:05:51,151  --  INFO -- Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-01-15 01:05:51,156  --  INFO -- Added job "automation_process" to job store "default"
2024-01-15 01:05:51,156  --  INFO -- Scheduler started
2024-01-15 01:06:04,647  --  INFO -- Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-01-15 01:06:04,649  --  INFO -- Added job "automation_process" to job store "default"
2024-01-15 01:06:04,649  --  INFO -- Scheduler started
2024-01-15 01:06:15,648  --  INFO -- Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-01-15 01:06:15,650  --  INFO -- Added job "automation_process" to job store "default"
2024-01-15 01:06:15,650  --  INFO -- Scheduler started
2024-01-15 01:07:00,014  --  INFO -- Running job "automation_process (trigger: cron[day_of_week='mon-sun', hour='1', minute='7'], next run at: 2024-01-15 01:07:00 WAT)" (scheduled at 2024-01-15 01:07:00+01:00)
2024-01-15 01:07:59,259  --  INFO -- Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-01-15 01:07:59,261  --  INFO -- Added job "automation_process" to job store "default"
2024-01-15 01:07:59,261  --  INFO -- Scheduler started
2024-01-15 01:08:00,014  --  INFO -- Running job "automation_process (trigger: cron[day_of_week='mon-sun', hour='1', minute='8'], next run at: 2024-01-15 01:08:00 WAT)" (scheduled at 2024-01-15 01:08:00+01:00)
2024-01-15 02:04:24,987  --  INFO -- Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-01-15 02:04:24,989  --  INFO -- Added job "automation_process" to job store "default"
2024-01-15 02:04:24,989  --  INFO -- Scheduler started
2024-01-15 12:18:20,827  --  INFO -- Handled Unknown Exception
2024-01-15 12:18:20,828  --  WARNING -- Retrying du
2024-01-15 12:19:57,713  --  INFO -- Handled Unknown Exception
2024-01-15 12:19:57,713  --  WARNING -- Retrying du
2024-01-15 12:26:07,706  --  INFO -- Handled Unknown Exception
2024-01-15 12:26:07,706  --  WARNING -- Retrying du
2024-01-15 12:36:56,611  --  INFO -- Handled Unknown Exception
2024-01-15 12:36:56,611  --  WARNING -- Retrying du
2024-01-15 12:39:41,808  --  INFO -- Handled Unknown Exception
2024-01-15 12:39:41,808  --  WARNING -- Retrying du
2024-01-15 12:42:13,919  --  ERROR -- Error terminating service process.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\common\service.py", line 170, in _terminate_process
    self.process.terminate()
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1671, in terminate
    _winapi.TerminateProcess(self._handle, 1)
OSError: [WinError 6] The handle is invalid
2024-01-15 12:46:24,039  --  INFO -- Handled Unknown Exception
2024-01-15 12:46:24,040  --  WARNING -- Retrying du
2024-01-15 12:58:26,134  --  INFO -- Handled Unknown Exception
2024-01-15 12:58:26,134  --  WARNING -- Retrying du
2024-01-15 13:30:37,177  --  INFO -- Handled Unknown Exception
2024-01-15 13:30:37,178  --  WARNING -- Retrying du
2024-01-15 13:39:25,117  --  INFO -- Handled Unknown Exception
2024-01-15 13:39:25,117  --  WARNING -- Retrying du
2024-01-15 14:20:12,976  --  INFO -- Handled Unknown Exception
2024-01-15 14:20:12,977  --  WARNING -- Retrying du
2024-01-15 16:59:59,919  --  INFO -- Handled Unknown Exception
2024-01-15 16:59:59,919  --  WARNING -- Retrying du
2024-01-15 18:14:04,726  --  ERROR -- Error terminating service process.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\common\service.py", line 170, in _terminate_process
    self.process.terminate()
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1671, in terminate
    _winapi.TerminateProcess(self._handle, 1)
OSError: [WinError 6] The handle is invalid
2024-01-15 22:10:22,811  --  ERROR -- Error terminating service process.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\common\service.py", line 170, in _terminate_process
    self.process.terminate()
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1671, in terminate
    _winapi.TerminateProcess(self._handle, 1)
OSError: [WinError 6] The handle is invalid
2024-01-15 22:10:24,922  --  ERROR -- Error terminating service process.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\common\service.py", line 170, in _terminate_process
    self.process.terminate()
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1671, in terminate
    _winapi.TerminateProcess(self._handle, 1)
OSError: [WinError 6] The handle is invalid
